/**
 * Anchor track client: mints a soulbound Core NFT on devnet by calling the
 * deployed `soulbound_nft` program, which CPIs into MPL Core's CreateV2.
 *
 * Run from inside 02-anchor-track (after `anchor build`):
 *
 *   ANCHOR_PROVIDER_URL=https://api.devnet.solana.com \
 *   ANCHOR_WALLET=$HOME/.config/solana/id.json \
 *   npx ts-node submissions/zaialamm/mint.ts
 */
import * as anchor from "@anchor-lang/core";
import { Keypair, PublicKey, SystemProgram } from "@solana/web3.js";
import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";
import { publicKey } from "@metaplex-foundation/umi";
import { fetchAsset } from "@metaplex-foundation/mpl-core";
import { SoulboundNft } from "../../target/types/soulbound_nft";

const MPL_CORE = new PublicKey("CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d");

const NAME = "Zai as Hiro Hamada (Anchor)";
const URI =
  "https://gist.githubusercontent.com/zaialamm/213830f29409d1816fda07c27b162f87/raw/zai-metadata.json";

const explorerAddress = (a: string) =>
  `https://explorer.solana.com/address/${a}?cluster=devnet`;
const explorerTx = (s: string) => `https://explorer.solana.com/tx/${s}?cluster=devnet`;

async function main() {
  // Reads ANCHOR_PROVIDER_URL and ANCHOR_WALLET from the environment.
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  // Program ID comes from target/idl/soulbound_nft.json (generated by `anchor build`).
  const program = anchor.workspace.SoulboundNft as anchor.Program<SoulboundNft>;

  console.log("Program ID:", program.programId.toBase58());
  console.log("Wallet:    ", provider.wallet.publicKey.toBase58());

  // The new NFT's address. MPL Core requires the new asset account to sign.
  const asset = Keypair.generate();

  const sig = await program.methods
    .mintSoulboundNft(NAME, URI)
    .accountsPartial({
      payer: provider.wallet.publicKey, // signs automatically via the provider
      asset: asset.publicKey, // fresh keypair, co-signs below
      owner: provider.wallet.publicKey, // the wallet the NFT is bound to forever
      mplCoreProgram: MPL_CORE,
      systemProgram: SystemProgram.programId,
    })
    .signers([asset])
    .rpc();

  console.log("\nAsset address:", asset.publicKey.toBase58());
  console.log("Signature:    ", sig);
  console.log("Asset:        ", explorerAddress(asset.publicKey.toBase58()));
  console.log("Transaction:  ", explorerTx(sig));

  // Anchor confirms at "processed"; wait for "confirmed" so the read-back sees it.
  const latest = await provider.connection.getLatestBlockhash("confirmed");
  await provider.connection.confirmTransaction({ signature: sig, ...latest }, "confirmed");

  // Read the asset back from devnet and confirm the freeze plugin is permanent.
  const umi = createUmi(provider.connection.rpcEndpoint, { commitment: "confirmed" });
  const onChain = await fetchAsset(umi, publicKey(asset.publicKey.toBase58()));
  const plugin = onChain.permanentFreezeDelegate;
  console.log("\nOn-chain check:");
  console.log("  name:            ", onChain.name);
  console.log("  owner:           ", onChain.owner.toString());
  console.log("  frozen:          ", plugin?.frozen);
  console.log("  plugin authority:", plugin?.authority.type);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
